services:
  - type: web
    name: nocbrewtest
    env: dotnet
    plan: free
    buildCommand: dotnet build NocBrewTest/NocBrewTest.csproj -c Release
    startCommand: dotnet NocBrewTest/bin/Release/net8.0/NocBrewTest.dll
    buildFilter:
      paths:
        - NocBrewTest/**
